blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/Australian-Food-and-Fibre/data-platform/tree/main/docs
    about: Check existing documentation before opening an issue
